### ISSUE TITLE
Weird cell execution

### ISSUE THREAD

**Issue by vpavlin** [CermakM/jupyter-nbrequirements#41]
**Describe the bug**
When `%requirements` executed in an empty notebook, the results are printed under new cell output and also the numbering for execution is wrong (there should be just [1], IMO)

![Screenshot from 2019-10-21 10-51-50](https://user-images.githubusercontent.com/4759808/67190918-15cdfd80-f3f1-11e9-877a-a37868ea14ce.png)

**To Reproduce**
1. Create new notebook with nbrequirements installed
2. run `%requirements`
3. observe the issue

**Expected behaviour**
Output is in the first cell output section, numbering is correct

**Comment by CermakM** [comment]
There are two issues in there, so 'weird' does sound like a reasonable way to put it.

1) The `execution count` (the number on the left) increments arbitrarily

That is due to the fact that there are multiple Python-JS communications happening in the backend and for each of them, this number is incremented.

It doesn't have an impact on the functionality, but it is indeed quite annoying and will require some additional thoughts about how to handle that.

2) The output of the cell is appended to the following cell

This happens due to the `<SHIFT>+Enter` combo which you probably executed, that is 'Run and Select cell below', on single-cell execution, this cannot happen.

This is because of the former issue, the first communication is exchanged, then the 'and select cell below' happens and before the execution finishes completely, a different cell is selected.

This is fixed in [jupyter-require v0.4.0](https://github.com/CermakM/jupyter-require/releases/tag/v0.4.0), please, try to update to the latest release and see if this part of the issue has been fixed.

**Comment by CermakM** [comment]
Both of these issues should now be fixed.
